apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: deimos
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80       # Service port
      targetPort: 80 # Container port (Nginx)
      nodePort: 30100 # External port (you can change this)